# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aac24c0423598a01b0963c51ef12dbb85f6a426d9eb003ef2451ace2f51cc500f73b79d5fc5c1903ca4efa3422f101d2976d3d84ea1dfc1a3e7b2ad9d65d0066

test:
  secret_key_base: 05b50896b3794de4f05147fc74c6e743ad8c46b0beeaae81fd75285bec1cb5e0901a8df51af01386bdc990f8de8b2299127f77f5871e5f8b31bd0b9780fe23e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
